CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Manager" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text NOT NULL,
    "Contact" text NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Manager" PRIMARY KEY ("Id")
);

CREATE TABLE "Patners_type" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Patners_types" text NOT NULL,
    CONSTRAINT "PK_Patners_type" PRIMARY KEY ("Id")
);

CREATE TABLE "Product_type" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Product_types" text NOT NULL,
    "Ratio_Product_types" text NOT NULL,
    CONSTRAINT "PK_Product_type" PRIMARY KEY ("Id")
);

CREATE TABLE "Partners" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Patners_Type_id" bigint NOT NULL,
    "Patners_Type_name" text NOT NULL,
    "Director" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "Addres_Partners" text NOT NULL,
    "INN" text NOT NULL,
    "Rate" bigint NOT NULL,
    CONSTRAINT "PK_Partners" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Partners_Patners_type_Patners_Type_id" FOREIGN KEY ("Patners_Type_id") REFERENCES "Patners_type" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Product" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Product_typeId" bigint NOT NULL,
    "Name_Product" text NOT NULL,
    "Артикул" bigint NOT NULL,
    "Min_cost_" double precision NOT NULL,
    CONSTRAINT "PK_Product" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Product_Product_type_Product_typeId" FOREIGN KEY ("Product_typeId") REFERENCES "Product_type" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PartnerProduct" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PartnersId" bigint NOT NULL,
    "ProductId" bigint NOT NULL,
    "Count" bigint NOT NULL,
    CONSTRAINT "PK_PartnerProduct" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PartnerProduct_Partners_PartnersId" FOREIGN KEY ("PartnersId") REFERENCES "Partners" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PartnerProduct_Product_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Product" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Requst" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ProductionId" bigint NOT NULL,
    "PartnersId" bigint NOT NULL,
    "ManagerId" bigint NOT NULL,
    "Count" bigint NOT NULL,
    "Date" text NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "PK_Requst" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Requst_Manager_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "Manager" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Requst_Partners_PartnersId" FOREIGN KEY ("PartnersId") REFERENCES "Partners" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Requst_Product_ProductionId" FOREIGN KEY ("ProductionId") REFERENCES "Product" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_PartnerProduct_PartnersId" ON "PartnerProduct" ("PartnersId");

CREATE INDEX "IX_PartnerProduct_ProductId" ON "PartnerProduct" ("ProductId");

CREATE INDEX "IX_Partners_Patners_Type_id" ON "Partners" ("Patners_Type_id");

CREATE INDEX "IX_Product_Product_typeId" ON "Product" ("Product_typeId");

CREATE INDEX "IX_Requst_ManagerId" ON "Requst" ("ManagerId");

CREATE INDEX "IX_Requst_PartnersId" ON "Requst" ("PartnersId");

CREATE INDEX "IX_Requst_ProductionId" ON "Requst" ("ProductionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250411072011_news', '9.0.4');

COMMIT;

